package com.miaoshaproject.dataobject;

import java.util.Date;

public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.id
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.prom_name
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    private String promName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.start_date
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.item_id
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.prom_item_price
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    private Double promItemPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.id
     *
     * @return the value of promo.id
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.id
     *
     * @param id the value for promo.id
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.prom_name
     *
     * @return the value of promo.prom_name
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public String getPromName() {
        return promName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.prom_name
     *
     * @param promName the value for promo.prom_name
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public void setPromName(String promName) {
        this.promName = promName == null ? null : promName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.start_date
     *
     * @return the value of promo.start_date
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.start_date
     *
     * @param startDate the value for promo.start_date
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.item_id
     *
     * @return the value of promo.item_id
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.item_id
     *
     * @param itemId the value for promo.item_id
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.prom_item_price
     *
     * @return the value of promo.prom_item_price
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public Double getPromItemPrice() {
        return promItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.prom_item_price
     *
     * @param promItemPrice the value for promo.prom_item_price
     *
     * @mbg.generated Wed Mar 13 14:53:31 CST 2024
     */
    public void setPromItemPrice(Double promItemPrice) {
        this.promItemPrice = promItemPrice;
    }
}