package com.miaoshaproject.dataobject;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.sequence_name
     *
     * @mbg.generated Mon Mar 11 15:32:29 CST 2024
     */
    private String sequenceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.current_value
     *
     * @mbg.generated Mon Mar 11 15:32:29 CST 2024
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Mon Mar 11 15:32:29 CST 2024
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.sequence_name
     *
     * @return the value of sequence_info.sequence_name
     *
     * @mbg.generated Mon Mar 11 15:32:29 CST 2024
     */
    public String getSequenceName() {
        return sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.sequence_name
     *
     * @param sequenceName the value for sequence_info.sequence_name
     *
     * @mbg.generated Mon Mar 11 15:32:29 CST 2024
     */
    public void setSequenceName(String sequenceName) {
        this.sequenceName = sequenceName == null ? null : sequenceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.current_value
     *
     * @return the value of sequence_info.current_value
     *
     * @mbg.generated Mon Mar 11 15:32:29 CST 2024
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.current_value
     *
     * @param currentValue the value for sequence_info.current_value
     *
     * @mbg.generated Mon Mar 11 15:32:29 CST 2024
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbg.generated Mon Mar 11 15:32:29 CST 2024
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbg.generated Mon Mar 11 15:32:29 CST 2024
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}